name: unit test

on:
  push:
    branches: [master, dev, ci/**]
  pull_request:
    branches: [master, dev, ci/**]
  workflow_dispatch:
    # Keep this to allow for triggering manually

jobs:
  unit-test:
    strategy:
      matrix:
        node-version:
          # currently devDependencies require node>=8.9
          - 8
          - 10
          # - 12 # skip
          # - 14 # skip
          # - 16 # skip
          # - 18 # skip
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Fix nyc coverage report with node8
        run: >
          npm install --no-save
          istanbul-lib-coverage@3.2.0
          istanbul-lib-instrument@5.2.1
          istanbul-lib-report@3.0.0
          istanbul-reports@3.1.5
      - name: Test
        run: npm test

      - name: Update Coverage Badge
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.node-version == 8 }}
        uses: we-cli/coverage-badge-action@main
